"""User registration screen for setup wizard.

Shown to non-admin users connecting to a remote multi-user Thoth server.
They enter the server URL and their API token (obtained from the admin),
verify the connection, and get their user info saved to local settings.
"""

from __future__ import annotations

import asyncio
from typing import Any

import httpx
from loguru import logger
from textual.app import ComposeResult
from textual.containers import Vertical
from textual.widgets import Button, Input, Label, Static

from .base import BaseScreen


class UserRegistrationScreen(BaseScreen):
    """Wizard screen for registering with a remote multi-user Thoth server."""

    def __init__(self) -> None:
        """Initialize user registration screen."""
        super().__init__(
            title='Connect to Thoth Server',
            subtitle='Enter your server URL and API token',
        )
        self.server_url: str = ''
        self.api_token: str = ''
        self.user_info: dict[str, Any] | None = None

    def compose_content(self) -> ComposeResult:
        """Compose user registration content."""
        yield Static(
            'Connect to a shared Thoth server. Your admin will provide the '
            'server URL and your personal API token.\n\n'
            'The token identifies you to the server and scopes all data '
            '(papers, agents, research questions) to your account.',
            classes='help-text',
        )

        with Vertical(classes='form-section'):
            yield Label('Thoth Server URL', classes='field-label')
            yield Input(
                placeholder='https://thoth.yourlab.com:8080',
                id='server-url-input',
            )

        with Vertical(classes='form-section'):
            yield Label('Your API Token', classes='field-label')
            yield Label(
                'The token starts with "thoth_" and was generated by the admin '
                'when your account was created.',
                classes='field-description',
            )
            yield Input(
                placeholder='thoth_...',
                password=True,
                id='token-input',
            )

        yield Button('Verify Connection', id='verify-btn', variant='primary')

        if self.user_info:
            yield Static(
                f'✓ Connected as: {self.user_info.get("username", "?")} '
                f'(vault: {self.user_info.get("vault_path", "?")})',
                id='connection-status',
                classes='success-box',
            )

    def on_button_pressed(self, event: Button.Pressed) -> None:
        """Handle button presses."""
        if event.button.id == 'verify-btn':
            asyncio.get_event_loop().run_until_complete(self._verify_connection())
        elif event.button.id == 'next':
            if not self.user_info:
                self.show_error('Please verify your connection first.')
                return
            self.dismiss(
                {
                    'server_url': self.server_url,
                    'api_token': self.api_token,
                    'user_info': self.user_info,
                }
            )
        elif event.button.id == 'back':
            self.app.pop_screen()

    async def _verify_connection(self) -> None:
        """Verify connection to the Thoth server using the API token."""
        url_input = self.query_one('#server-url-input', Input)
        token_input = self.query_one('#token-input', Input)

        self.server_url = url_input.value.strip().rstrip('/')
        self.api_token = token_input.value.strip()

        if not self.server_url:
            self.show_error('Server URL is required.')
            return

        if not self.api_token.startswith('thoth_'):
            self.show_error('API token must start with "thoth_".')
            return

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.get(
                    f'{self.server_url}/auth/me',
                    headers={'Authorization': f'Bearer {self.api_token}'},
                )

                if response.status_code == 200:
                    self.user_info = response.json()
                    self.refresh()
                    logger.info(
                        f'Verified connection as {self.user_info.get("username")}'
                    )
                elif response.status_code == 401:
                    self.show_error(
                        'Invalid token. Check that it was copied correctly.'
                    )
                elif response.status_code == 404:
                    self.show_error(
                        'Server not found or /auth/me endpoint missing. '
                        'Check the server URL and that multi-user mode is enabled.'
                    )
                else:
                    self.show_error(
                        f'Server returned {response.status_code}. Check the server URL.'
                    )

        except httpx.ConnectError:
            self.show_error(
                f'Cannot reach {self.server_url}. '
                'Check the URL and that the server is running.'
            )
        except Exception as e:
            logger.error(f'Connection verification failed: {e}')
            self.show_error(f'Connection failed: {e}')
